### ISSUE TITLE
Feature request: multiple selections

### ISSUE THREAD

**Issue by eighthday** [sylvainjule/kirby-color-palette#11]
Love the plugin -  it would be handy if we can select more than one color, so we don't have to create multiple color palette fields.

**Comment by sylvainjule** [comment]
What'd be your use case for this?

**Comment by eighthday** [comment]
sorry, actually this would not even work for my usercase as I would not be able to control the order of the colors.

**Comment by sylvainjule** [comment]
Yes, that's what'd be tricky with multiple selections. I figure in this case it'd be easier to draft something from the multiselect field. Closing this ticket.
