### ISSUE TITLE
UI enhancement suggestions

### ISSUE THREAD

**Issue by VIPStephan** [sylvainjule/kirby-color-palette#12]
Suggestion 1: I have a color that’s very similar to the background color of the panel, so it’s barely visible in the panel. It would be nice to be able to add a custom border around the items. I thought that would be possible when using the structured object method but in fact, the indication of a selected item is removed completely when doing this.

So, I imagine that the user would be able to specify a border color around the items (or just a boolean setting to show a border around the color, which may default to black), so that light or barely visible colors can be spotted more easily.

Suggestion 2: The ability to add custom color names that are then shown in the panel (and possibly in templates, too). In the panel that could either be a tooltip type of indicator that shows the color name on mouseover, or it would be displayed below or to the side of the square. Or, and that might be a third suggestion: provide the option to show colors as a vertical list or dropdown select list (with names next to the color squares) rather than simple inline squares.

**Comment by sylvainjule** [comment]
Regarding suggestion 1: you can add any CSS style you want to the `.color-palette_input-color` selector in a custom panel css, you can even restrict it to your field name if you want to make it specific to a given field. It feels smoother than another plugin option.

I have suggestion 2 (tooltips) planned and already working for a custom implementation on another branch, just need to find the time to add it to master.

**Comment by VIPStephan** [comment]
Thanks for the quick response. Regarding suggestion 1: how about having a border as default with the option to _remove_ it with a custom panel CSS? I’ve solved it using a subtle inset box shadow, like `box-shadow: inset 0 0 1px rgba(0,0,0,.5);` and it looks very nice and subtle because it just tints the colors themselves and doesn’t add to the size of the items.

**Comment by sylvainjule** [comment]
Though I understand the need for some colors, I still think option 1 should be left to anyone's appreciation and is a very simple css line to add, I am personally not fond of working with this border and this plugin already have a lot of options. 🤔 

I'm adding tooltips now 👍

**Comment by VIPStephan** [comment]
Thanks, I understand. I’ve added a custom panel stylesheet and that does the trick as well.

And thanks for the tooltips. Just what the doctor ordered. :-)
