### ISSUE TITLE
Doesn't work with Imagemagick thumb driver

### ISSUE THREAD

**Issue by tristantbg** [sylvainjule/kirby-color-palette#4]
I got a 500 error :

```Call to undefined function dd()```

**Comment by sylvainjule** [comment]
Do you have any other plugin installed? The plugin doesn't have any `dd()` function, and seems to work for me with imagemagick.

**Comment by tristantbg** [comment]
You are right.

I have Kirby Focus installed and it overrides the Imagemagick driver with a dd() function !

Thank you for the fast check.
