### ISSUE TITLE
return value of palette

### ISSUE THREAD

**Issue by bnomei** [sylvainjule/kirby-color-palette#6]
`$selected = $page->palette(); #(string)`

stumbled upon this doing a arrayl key lookup on selected...
one might expect a `string` but its a `Field`. 
so `$page->palette()->value()` is needed to get a proper `string`.

maybe you could explain that just to make sure no kirby newbie gets lost.

otherwise great plugin. any donation links apart from the kirby paddle affilate link?

**Comment by sylvainjule** [comment]
I've updated the README!

With both the distinction between the FIeld object and its content string, and a donation link 🙂
