### ISSUE TITLE
DRY options

### ISSUE THREAD

**Issue by bnomei** [sylvainjule/kirby-color-palette#7]
not sure if one can inherit that from other fields, but for DRY reasons i would love to get the full dynamic and api options the select, checkboxes and multiselect fields provide.
https://getkirby.com/docs/reference/panel/fields/select#dynamic-options

**Comment by sylvainjule** [comment]
I've added the possibility to use dynamic options. Please give it a shot and feel free to reopen if you find any bug!

[Documented here](https://github.com/sylvainjule/kirby-color-palette#dynamic-options)

**Comment by bnomei** [comment]
thats awesome. thanks so much!
