### ISSUE TITLE
The plugin is missing one german translation

### ISSUE THREAD

**Issue by sylvainjule** [sylvainjule/kirby-color-palette#9]
Ping @jschopplich 👋

I've made [some changes](https://github.com/sylvainjule/kirby-color-palette#42-automatically-extract-colors-when-an-image-matches-a-template) that required a new translation:

```php
'palette.empty.template' => 'There is currently no image to extract colors from.',
```

Could you help me with its german translation? You can directly reply to this issue, I'll add it manually 🙂

**Comment by jschopplich** [comment]
Hello Sylvain. 🙂

Of course — here you go:

```php
'palette.empty.template' => 'Es gibt derzeit kein Bild, aus denen Farben extrahiert werden können.',
```

**Comment by sylvainjule** [comment]
Awesome, thank you! 👏
